spring:
  datasource:
    password: 5403
    url: jdbc:postgresql://localhost:5432/carrental
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  